version: '3.8'

services:

  backend:
    build:
      context: ./
    container_name: backend-pre
    ports:
      - "5001:5000"
    env_file:
      - ./env/.env.pre
    networks:
      - luhn-net
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db-pre
    environment:
      POSTGRES_USER: luhn_user
      POSTGRES_PASSWORD: luhn_pass
      POSTGRES_DB: luhn_db
    volumes:
      - dbdata-pre:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - luhn-net
    ports:
      - "5432:5432"

 

volumes:
  dbdata-pre:
  jenkins_home_pre:

networks:
  luhn-net:
