version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend-prod
    ports:
      - "5002:5000"
    env_file:
      - .env.prod
    networks:
      - luhn-net-prod
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db-prod
    environment:
      POSTGRES_USER: luhn_user
      POSTGRES_PASSWORD: luhn_pass
      POSTGRES_DB: luhn_db
    volumes:
      - dbdata-prod:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - luhn-net-prod

  adminer:
    image: adminer
    container_name: adminer-pre
    restart: always
    ports:
      - "8083:8080"
    networks:
      - luhn-net-prod

volumes:
  dbdata-prod:

networks:
  luhn-net-prod:
    external: true
